services:

  minecraf_server:
    image: itzg/minecraft-server:java21
    container_name: mc
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.21.5"
    volumes:
      - mc-data:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  mc-data:

